# Generated by Django 3.2.8 on 2021-10-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videofile_1', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videofile_2', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videofile_3', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videofile_4', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('videofile_5', models.FileField(blank=True, null=True, upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='product_video',
        ),
    ]
